// angular2-node-express-mongodb/src/client/app/components/account/account-view-page.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { UserService } from '../../services/user.service';

@Component({
    templateUrl: 'app/components/account/account-view-page.component.html'
})
export class AccountViewPageComponent implements OnInit {
    user: any;

    constructor(
        private _router: Router,
        private _authService: AuthService,
        private _userService: UserService
    ) { }

    ngOnInit() {
        this.user = {};

        let currentUser = this._authService.getCurrentUser();
        this._userService.getById(currentUser._id)
            .then(user => this.user = user);
    }

    remove(e: Event) {
        e.preventDefault();
        this._userService.remove(this.user._id)
            .then(() => {
                this._authService.logout();
                this._router.navigate(['/login']);
            });
    }
}

<section>
    <h1 class="title">Account</h1>

    <ul class="actions">
        <li><a routerLink="/account/edit">edit</a></li>
        <li><a routerLink="/account/password">change password</a></li>
        <li><a href="" (click)="remove($event)">delete</a></li>
    </ul>

    <div>
        <id-view-field label="" [value]="user.firstName + ' ' + user.lastName" class="bottom-border"></id-view-field>
        <id-view-field label="Username" [value]="user.username"></id-view-field>
        <id-view-field label="Email" [value]="user.email"></id-view-field>
        <id-view-field label="Joined" [value]="user.createdDate | idDateFormatter"></id-view-field>
    </div>
</section>

// react-es6-node-graphql-mongodb/src/client/components/account/accountViewPage.react.js
import React, {Component, PropTypes} from 'react';
import {Link} from 'react-router';
import moment from 'moment';
import authActions from '../../actions/authActions';
import userActions from '../../actions/userActions';
import {UserStore, UserEvents} from '../../stores/userStore';
import {AuthStore} from '../../stores/authStore';
import ViewField from '../common/viewField.react';

class AccountViewPage extends Component {
    static contextTypes = {
        router: PropTypes.object.isRequired
    }

    constructor(props) {
        super(props);
        this.state = {
            user: {}
        };
    }

    componentWillMount() {
        let userId = AuthStore.getCurrentUser()._id;
        UserStore.getUserById(userId)
            .done(user => {
                this.setState({ user: user });
            });

        UserStore.on(UserEvents.Delete, this._onDeleted);
    }

    componentWillUnmount() {
        UserStore.removeListener(UserEvents.Delete, this._onDeleted);
    }

    render() {
        return (
            <section>
                <h1 className="title">Account</h1>

                <ul className="actions">
                    <li><Link to="/account/edit">edit</Link></li>
                    <li><Link to="/account/password">change password</Link></li>
                    <li><a href="" onClick={this._remove}>delete</a></li>
                </ul>

                <div>
                    <ViewField label="" value={this.state.user.firstName + ' ' + this.state.user.lastName} className="bottom-border" />
                    <ViewField label="Username" value={this.state.user.username} />
                    <ViewField label="Email" value={this.state.user.email} />
                    <ViewField label="Joined" value={moment(this.state.user.createdDate).format('M/DD/YYYY')} />
                </div>
            </section>
        );
    }

    _onDeleted = (id) => {
        if (id === this.state.user._id) {
            setTimeout(() => {
                authActions.logout();
                this.context.router.push('/login');
            }, 1);
        }
    }

    _remove = (e) => {
        e.preventDefault();
        userActions.deleteUser(this.state.user._id);
    }
}

export default AccountViewPage;
