// angular2-node-express-mongodb/src/client/app/components/account/account-password-page.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { UserService } from '../../services/user.service';

@Component({
    templateUrl: 'app/components/account/account-password-page.component.html'
})
export class AccountPasswordPageComponent implements OnInit {
    user: any;
    form: FormGroup;
    formSubmitted: boolean;
    passwords: any;

    constructor(
        private _router: Router,
        private _authService: AuthService,
        private _userService: UserService
    ) { }

    ngOnInit() {
        this.user = {};
        this.passwords = {
            oldPassword: '',
            newPassword: '',
            confirmPassword: ''
        };

        let currentPasswordValidator = (c: FormControl) => {
            return c.value === this.user.password ? null : {
                passwordIncorect: 'password is incorrect'
            };
        };

        let confirmPasswordValidator = (c: FormControl) => {
            return c.value === this.passwords.newPassword ? null : {
                mustMatch: 'passwords must match'
            };
        };

        this.form = new FormGroup({
            oldPassword: new FormControl('', [Validators.required, currentPasswordValidator]),
            newPassword: new FormControl('', Validators.required),
            confirmPassword: new FormControl('', [Validators.required, confirmPasswordValidator])
        });

        let currentUser = this._authService.getCurrentUser();
        this._userService.getById(currentUser._id)
            .then(user => this.user = user);
    }

    cancel() {
        this._router.navigate(['/account']);
    }

    save() {
        this.formSubmitted = true;
        if (this.form.valid) {
            this.user.password = this.passwords.newPassword;
            this._authService.updateUser(this.user)
                .then(success => {
                    if (success) {
                        this._router.navigate(['/account']);
                    } else {
                        console.log('user update failed');
                    }
                });
        }
    }
}

<section>
    <h1 class="title">Account: Change Password</h1>

    <ul class="actions">
        <li><a routerLink="/account">back</a></li>
    </ul>

    <id-view-field label="" [value]="user.firstName + ' ' + user.lastName" class="bottom-border"></id-view-field>

    <form [formGroup]="form" (ngSubmit)="save()">
        <id-text-input formControlName="oldPassword" label="Old Password" class="password" type="password"
            [(ngModel)]="passwords.oldPassword"
            [errors]="formSubmitted ? form.controls.oldPassword.errors : {}"
            [showErrorMessage]="form.controls.oldPassword.errors && !form.controls.oldPassword.errors.required">
        </id-text-input>

        <id-text-input formControlName="newPassword" label="New Password" class="password" type="password"
            [(ngModel)]="passwords.newPassword"
            [errors]="formSubmitted ? form.controls.newPassword.errors : {}"
            [showErrorMessage]="form.controls.newPassword.errors && !form.controls.newPassword.errors.required">
        </id-text-input>

        <id-text-input formControlName="confirmPassword" label="Confirm" class="password" type="password"
            [(ngModel)]="passwords.confirmPassword"
            [errors]="formSubmitted ? form.controls.confirmPassword.errors : {}"
            [showErrorMessage]="form.controls.confirmPassword.errors && !form.controls.confirmPassword.errors.required">
        </id-text-input>

        <fieldset class="form-button-group">
            <button type="submit" class="form-button button-default">save</button>
            <button type="button" class="form-button" (click)="cancel()">cancel</button>
        </fieldset>
    </form>
</section>

// react-es6-node-graphql-mongodb/src/client/components/account/accountPasswordPage.react.js
import React, {Component, PropTypes} from 'react';
import {Link} from 'react-router';
import moment from 'moment';
import userActions from '../../actions/userActions';
import {UserStore} from '../../stores/userStore';
import {AuthStore} from '../../stores/authStore';
import ViewField from '../common/viewField.react';
import TextInput from '../common/textInput.react';

class AccountPasswordPage extends Component {
    static contextTypes = {
        router: PropTypes.object.isRequired
    }

    constructor(props) {
        super(props);
        this.state = {
            user: {
                username: '',
                firstName: '',
                lastName: '',
                email: ''
            },
            passwords: {
                oldPassword: '',
                newPassword: '',
                confirmPassword: ''
            },
            errors: {}
        };
    }

    componentWillMount() {
        let userId = AuthStore.getCurrentUser()._id;
        UserStore.getUserById(userId)
            .done(user => {
                this.setState({ user: user });
            });
    }

    render() {
        return (
            <section>
                <h1 className="title">Account: Change Password</h1>

                <ul className="actions">
                    <li><Link to="/account">back</Link></li>
                </ul>

                <ViewField label="" value={this.state.user.firstName + ' ' + this.state.user.lastName} className="bottom-border" />

                <form name="changePasswordForm" onSubmit={e => e.preventDefault()}>
                    <TextInput name="oldPassword" label="Old Password" className="password" type="password"
                        value={this.state.passwords.oldPassword}
                        onChange={this._onChange}
                        error={this.state.errors.oldPassword}
                        showErrorMessage={true} />

                    <TextInput name="newPassword" label="New Password" className="password" type="password"
                        value={this.state.passwords.newPassword}
                        onChange={this._onChange}
                        error={this.state.errors.newPassword}
                        showErrorMessage={true} />

                    <TextInput name="confirmPassword" label="Confirm" className="password" type="password"
                        value={this.state.passwords.confirmPassword}
                        onChange={this._onChange}
                        error={this.state.errors.confirmPassword}
                        showErrorMessage={true} />

                    <fieldset className="form-button-group">
                        <button type="button" className="form-button button-default" onClick={this._save}>save</button>
                        <button type="button" className="form-button" onClick={this._cancel}>cancel</button>
                    </fieldset>
                </form>
            </section>
        );
    }

    _onChange = (e) => {
        var field = e.target.name;
        var value = e.target.value;
        this.state.passwords[field] = value;
        this.setState({passwords: this.state.passwords});
    }

    _save = (e) => {
        e.preventDefault();

        if (!this._formIsValid()) {
            return;
        }

        this.state.user.password = this.state.passwords.newPassword;
        userActions.updateUser(this.state.user);
        this.context.router.push('/account');
    }

    _cancel = (e) => {
        e.preventDefault();
        this.context.router.push('/account');
    }

    _formIsValid = () => {
        let formIsValid = true;
        let requiredField = ['oldPassword', 'newPassword'];

        this.state.errors = {};
        for (let f of requiredField) {
            if (this.state.passwords[f].trim().length === 0) {
                this.state.errors[f] = 'required';
                formIsValid = false;
            }
        }
        if (this.state.passwords.oldPassword !== this.state.user.password) {
            this.state.errors.oldPassword = 'password is incorrect';
            formIsValid = false;
        }
        if (this.state.passwords.newPassword !== this.state.passwords.confirmPassword) {
            this.state.errors.confirmPassword = 'passwords must match';
            formIsValid = false;
        }

        this.setState({errors: this.state.errors});
        return formIsValid;
    }
}

export default AccountPasswordPage;
