// angular2-node-express-mongodb/src/client/app/components/people/person-list-page.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { UserService } from '../../services/user.service';
import { Util } from '../../blocks/util/util.service';

@Component({
    templateUrl: 'app/components/people/person-list-page.component.html'
})
export class PersonListPageComponent implements OnInit {
    private _sortDesc: boolean;

    people: any[];
    showFilter: boolean;
    filter: string;

    constructor(
        private _router: Router,
        private _userService: UserService,
        private _util: Util) {
    }

    ngOnInit() {
        this._sortDesc = false;
        this.people = [];
        this.showFilter = false;
        this.filter = '';

        this._userService.getAll()
            .then(people => {
                this._sortPeople(people);
                this.people = people;
            });
    }

    viewPerson(person: any) {
        this._router.navigate(['/people', person._id]);
    }

    reverseSortOrder(e: Event) {
        e.preventDefault();
        this._sortDesc = !this._sortDesc;
        this._sortPeople(this.people);
    }

    toggleFilter(e: Event) {
        e.preventDefault();
        this.showFilter = !this.showFilter;
        if (!this.showFilter) {
            this.filter = '';
        }
    }

    onFilterChange(value: string) {
        this.filter = value;
    }

    toList(arr: string[]) {
        return this._util.arrayToString(arr);
    }

    private _sortPeople(people: any[]) {
        people.sort(this._util.sortCompareFunc('lastName', this._sortDesc, (i: string) => i.toUpperCase()));
    }
}

<id-header></id-header>

<section>
    <h1 class="title">People</h1>

    <ul class="actions">
        <li><a href="" (click)="reverseSortOrder($event)">sort</a></li>
        <li><a href="" (click)="toggleFilter($event)">filter</a></li>
    </ul>

    <id-list-filter *ngIf="showFilter" [(filter)]="filter" (close)="showFilter = false"></id-list-filter>

    <ul class="person-list" *ngIf="people.length > 0">
        <li *ngFor="let person of people | idUserFilter:filter">
            <button (click)="viewPerson(person)">
                <span class="person-list-full-name">{{person.firstName}} {{person.lastName}}</span>
                <span class="person-list-info">username: {{person.username}}</span>
                <span class="person-list-info">email: {{person.email}}</span>
            </button>
        </li>
    </ul>
</section>

// react-es6-node-graphql-mongodb/src/client/components/people/personListPage.react.js
import React, {Component, PropTypes} from 'react';
import {Link} from 'react-router';
import util from '../../utilities/util';
import {UserStore} from '../../stores/userStore';
import ListFilter from '../common/listFilter.react';

class PersonListPage extends Component {
    static contextTypes = {
        router: PropTypes.object.isRequired
    }

    constructor() {
        super();
        this._sortDesc = false;
        this.state = {
            people: [],
            filteredPeople: [],
            filterStr: '',
            showFilter: false
        };
    }

    componentWillMount() {
        UserStore.getUserList()
            .done(users => {
                this._sortPeople(users);
                this.setState({ people: users, filteredPeople: users.slice() });
            });
    }

    render() {
        let content = this.state.filteredPeople.map(person => {
            return (
                <li key={person._id}>
                    <button onClick={this._viewPerson.bind(this, person._id)}>
                        <span className="person-list-full-name">{person.firstName} {person.lastName}</span>
                        <span className="person-list-info">username: {person.username}</span>
                        <span className="person-list-info">email: {person.email}</span>
                    </button>
                </li>
            );
        });

        return (
            <section>
                <h1 className="title">People</h1>

                <ul className="actions">
                    <li><a href="" onClick={this._reverseSortOrder}>sort</a></li>
                    <li><a href="" onClick={this._toggleFilter}>filter</a></li>
                </ul>

                {(() => {
                    if (this.state.showFilter) {
                        return (<ListFilter filterStr={this.state.filterStr} onChange={this._onFilterChange} />);
                    }
                })()}

                <ul className="person-list">
                    {content}
                </ul>
            </section>
        );
    }

    _viewPerson = (id, e) => {
        e.preventDefault();
        this.context.router.push('/people/' + id);
    }

    _reverseSortOrder = (e) => {
        e.preventDefault();
        this._sortDesc = !this._sortDesc;
        this._sortPeople(this.state.people);
        this.setState({ people: this.state.people });
    }

    _sortPeople = (people) => {
        people.sort(util.sortCompareFunc('lastName', this._sortDesc, i => i.toUpperCase()));
    }

    _toggleFilter = (e) => {
        e.preventDefault();
        this.setState({ showFilter: !this.state.showFilter });
        if (this.state.showFilter) {
            this.setState({ filterStr: '', filteredPeople: this.state.people.slice() });
        }
    }

    _onFilterChange = (e) => {
        let str = e.target.value.toLowerCase();
        this.state.filteredPeople = this.state.people.filter(person => {
            return person.username.toLowerCase().indexOf(str) >= 0 ||
                person.firstName.toLowerCase().indexOf(str) >= 0 ||
                person.lastName.toLowerCase().indexOf(str) >= 0 ||
                person.email.toLowerCase().indexOf(str) >= 0;
        });
        this.setState({ filterStr: str, filteredPeople: this.state.filteredPeople });
    }

    _toList = (arr, prop) => {
        return util.arrayToString(arr, prop);
    }
}

export default PersonListPage;
