// angular2-node-express-mongodb/src/client/app/components/ideas/idea-details.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Util } from '../../blocks/util/util.service';
import { IIdea, IComment } from '../../services/idea.service';

@Component({
    selector: 'id-idea-details',
    templateUrl: 'app/components/ideas/idea-details.component.html'
})
export class IdeaDetailsComponent {
    @Input() idea: IIdea;
    @Output() ideaChange = new EventEmitter<IIdea>()

    constructor(private _util: Util) { }

    toList(arr: any[], isProposerArr: boolean) {
        if (arr.length === 0) {
            return null;
        }
        if (isProposerArr) {
            arr = arr.map(p => p.firstName + ' ' + p.lastName);
        }
        return this._util.arrayToString(arr);
    }

    onCommentsChange() {
        this.ideaChange.emit(this.idea);
    }
}

<div>
    <id-view-field label="" [value]="idea.name" class="bottom-border"></id-view-field>
    <id-view-field label="Summary" [value]="idea.summary" class="bottom-border linebreaks"></id-view-field>
    <id-view-field label="Benefits" [value]="idea.benefits" class="bottom-border linebreaks"></id-view-field>
    <id-view-field label="Details" [value]="idea.details" class="bottom-border linebreaks"></id-view-field>
    <id-view-field label="Proposers" [value]="toList(idea.proposers, true)"></id-view-field>
    <id-view-field label="Skills" [value]="toList(idea.skills)"></id-view-field>
    <id-view-field label="Technologies" [value]="toList(idea.technologies)"></id-view-field>
    <id-view-field label="Tags" [value]="toList(idea.tags)"></id-view-field>
    <id-view-field label="Votes" [value]="idea.votes.length" class="bottom-border-spaced"></id-view-field>

    <id-comments-section [(comments)]="idea.comments" (commentsChange)="onCommentsChange()"></id-comments-section>
</div>

// react-es6-node-graphql-mongodb/src/client/components/ideas/sub/ideaDetails.react.js
import React, {Component, PropTypes} from 'react';
import util from '../../../utilities/util';
import ViewField from '../../common/viewField.react';
import CommentsSection from './commentsSection.react';

class IdeaDetails extends Component {
    static propTypes = {
        idea: PropTypes.object.isRequired,
        onChange: PropTypes.func.isRequired
    }

    render() {
        return (
            <div>
                <ViewField label="" value={this.props.idea.name} className="bottom-border" />
                <ViewField label="Summary" value={this.props.idea.summary} className="bottom-border linebreaks" />
                <ViewField label="Benefits" value={this.props.idea.benefits} className="bottom-border linebreaks" />
                <ViewField label="Details" value={this.props.idea.details} className="bottom-border linebreaks" />
                <ViewField label="Proposers" value={this._toList(this.props.idea.proposers, p => p.firstName + ' ' + p.lastName)} />
                <ViewField label="Skills" value={this._toList(this.props.idea.skills)} />
                <ViewField label="Technologies" value={this._toList(this.props.idea.technologies)} />
                <ViewField label="Tags" value={this._toList(this.props.idea.tags)} />
                <ViewField label="Votes" value={'' + this.props.idea.votes.length} className="bottom-border-spaced" />

                <CommentsSection comments={this.props.idea.comments} onChange={this.props.onChange} />
            </div>
        );
    }

    _toList = (arr, predicate) => {
        return util.arrayToString(arr, null, predicate);
    }
}

export default IdeaDetails;
