// angular2-node-express-mongodb/src/client/app/components/ideas/idea-form.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { IUser } from '../../services/user.service';

@Component({
    selector: 'id-idea-form',
    templateUrl: 'app/components/ideas/idea-form.component.html'
})
export class IdeaFormComponent {
    @Input() idea: any;
    @Input() skills: any[];
    @Input() technologies: any[];
    @Input() tags: any[];
    @Input() people: IUser[] = [];
    @Input() showProposers: boolean;
    @Output() addProposer = new EventEmitter<void>();
    @Output() save = new EventEmitter<any>();
    @Output() cancel = new EventEmitter<void>();

    form: FormGroup;
    formSubmitted: boolean;

    constructor(private _formBuilder: FormBuilder) { }

    ngOnInit() {
        this.form = this._formBuilder.group({
            name: ['', Validators.required],
            summary: ['', Validators.required],
            benefits: ['', Validators.required],
            details: ['', Validators.required]
        });
    }

    saveIdea() {
        this.formSubmitted = true;
        if (this.form.valid) {
            this.save.emit(this.idea);
        }
    }

    cancelIdea() {
        this.cancel.emit();
    }

    onAddProposer() {
        this.addProposer.emit();
    }

    onRemoveProposer(proposer: IUser) {
        var index = this.idea.proposers.indexOf(proposer);
        this.idea.proposers.splice(index, 1);
    }
}

<form [formGroup]="form">
    <id-text-input name="name" label="Name" class="name"
        [(ngModel)]="idea.name"
        formControlName="name"
        [errors]="formSubmitted ? form.controls.name.errors : {}"
        [autoFocus]="true">
    </id-text-input>

    <id-text-area name="summary" label="Summary" class="desc"
        [(ngModel)]="idea.summary"
        formControlName="summary"
        [errors]="formSubmitted ? form.controls.summary.errors : {}"
        [autoSize]="true">
    </id-text-area>

    <id-text-area name="benefits" label="Benefits" class="desc"
        [(ngModel)]="idea.benefits"
        formControlName="benefits"
        [errors]="formSubmitted ? form.controls.benefits.errors : {}"
        [autoSize]="true">
    </id-text-area>

    <id-text-area name="details" label="Details" class="desc"
        [(ngModel)]="idea.details"
        formControlName="details"
        [errors]="formSubmitted ? form.controls.details.errors : {}"
        [autoSize]="true">
    </id-text-area>

    <id-proposers-section *ngIf="showProposers"
        [proposers]="idea.proposers"
        (remove)="onRemoveProposer($event)"
        (add)="onAddProposer()">
    </id-proposers-section>

    <id-skills-section [(skills)]="idea.skills" [allSkills]="skills"></id-skills-section>

    <id-technologies-section [(technologies)]="idea.technologies" [allTechnologies]="technologies"></id-technologies-section>

    <id-tags-section [(tags)]="idea.tags" [allTags]="tags"></id-tags-section>

    <fieldset class="form-button-group">
        <button type="button" class="form-button button-default" (click)="saveIdea()">save</button>
        <button type="button" class="form-button" (click)="cancelIdea()">cancel</button>
    </fieldset>
</form>

// react-es6-node-graphql-mongodb/src/client/components/ideas/sub/ideaForm.react.js
import React, {Component, PropTypes} from 'react';
import domUtil from '../../../utilities/domUtil';
import TextInput from '../../common/textInput.react';
import TextArea from '../../common/textArea.react';
import ProposersSection from './proposersSection.react';
import SkillsSection from './skillsSection.react';
import TechnologiesSection from './technologiesSection.react';
import TagsSection from './tagsSection.react';

class IdeaForm extends Component {
    static propTypes = {
        idea: PropTypes.object.isRequired,
        skills: PropTypes.arrayOf(PropTypes.string).isRequired,
        technologies: PropTypes.arrayOf(PropTypes.string).isRequired,
        tags: PropTypes.arrayOf(PropTypes.string).isRequired,
        errors: PropTypes.object,
        onChange: PropTypes.func.isRequired,
        onSave: PropTypes.func.isRequired,
        onCancel: PropTypes.func.isRequired,
        showProposers: PropTypes.bool,
        onAddProposer: PropTypes.func
    }

    // componentDidMount(prevProps, prevState) {
    //     domUtil.autoSize('.auto-size');
    // }

    render() {
        return (
            <form name="editIdeaForm" onSubmit={e => e.preventDefault()}>
                <TextInput name="name" label="Name" className="name"
                    value={this.props.idea.name}
                    onChange={this._onChange}
                    error={this.props.errors.name}
                    autoFocus={true} />

                <TextArea name="summary" label="Summary" className="desc"
                    value={this.props.idea.summary}
                    onChange={this._onChange}
                    error={this.props.errors.summary}
                    autoSize={true} />

                <TextArea name="benefits" label="Benefits" className="desc"
                    value={this.props.idea.benefits}
                    onChange={this._onChange}
                    error={this.props.errors.benefits}
                    autoSize={true} />

                <TextArea name="details" label="Details" className="desc"
                    value={this.props.idea.details}
                    onChange={this._onChange}
                    error={this.props.errors.details}
                    autoSize={true} />

                {(() => {
                    if (this.props.showProposers) {
                        return (
                            <ProposersSection proposers={this.props.idea.proposers}
                                onRemove={this._onRemove}
                                onAdd={this.props.onAddProposer} />
                        );
                    }
                })()}

                <SkillsSection skills={this.props.idea.skills}
                    allSkills={this.props.skills}
                    onChange={this.props.onChange} />

                <TechnologiesSection technologies={this.props.idea.technologies}
                    allTechnologies={this.props.technologies}
                    onChange={this.props.onChange} />

                <TagsSection tags={this.props.idea.tags}
                    allTags={this.props.tags}
                    onChange={this.props.onChange} />

                <fieldset className="form-button-group">
                    <button type="button" className="form-button button-default" onClick={this.props.onSave}>save</button>
                    <button type="button" className="form-button" onClick={this.props.onCancel}>cancel</button>
                </fieldset>
            </form>
        );
    }

    _onChange = (e) => {
        var field = e.target.name;
        var value = e.target.value;
        this.props.onChange(field, value);
    }

    _onRemove = (proposer, e) => {
        e.preventDefault();
        var index = this.props.idea.proposers.indexOf(proposer);
        this.props.idea.proposers.splice(index, 1);
        this.props.onChange('proposers', this.props.idea.proposers);
    }
}

export default IdeaForm;
