// react-es6-node-graphql-mongodb/src/client/components/login/signupPage.react.js
import React, {Component, PropTypes} from 'react';
import {Link} from 'react-router';
import authActions from '../../actions/authActions';
import {AuthStore, AuthEvents} from '../../stores/authStore';
import TextInput from '../common/textInput.react';

class SignupPage extends Component {
    static contextTypes = {
        router: PropTypes.object.isRequired
    }

    constructor(props) {
        super(props);
        this.state = {
            signup: {
                username: '',
                firstName: '',
                lastName: '',
                email: '',
                password: '',
                confirmPassword: ''
            },
            errors: {}
        };
    }

    componentWillMount() {
        AuthStore.on(AuthEvents.Signup, this._onSignup);
        AuthStore.on(AuthEvents.Login, this._onLogin);
    }

    componentWillUnmount() {
        AuthStore.removeListener(AuthEvents.Signup, this._onSignup);
        AuthStore.removeListener(AuthEvents.Login, this._onLogin);
    }

    render() {
        return (
            <section>
                <h1 className="title">Create Account</h1>

                <ul className="actions">
                    <li><Link to="login">back</Link></li>
                </ul>

                <form name="createAccountForm" onSubmit={e => e.preventDefault()}>
                    <TextInput name="username" label="Username" className="id"
                        value={this.state.signup.username}
                        onChange={this._onChange}
                        error={this.state.errors.username}
                        showErrorMessage={this.state.errors.username && this.state.errors.username !== 'required'}
                        autoFocus={true} />

                    <TextInput name="firstName" label="First Name" className="name"
                        value={this.state.signup.firstName}
                        onChange={this._onChange}
                        error={this.state.errors.firstName} />

                    <TextInput name="lastName" label="Last Name" className="name"
                        value={this.state.signup.lastName}
                        onChange={this._onChange}
                        error={this.state.errors.lastName} />

                    <TextInput name="email" label="Email" className="email" type="email"
                        value={this.state.signup.email}
                        onChange={this._onChange}
                        error={this.state.errors.email} />

                    <TextInput name="password" label="Password" className="password" type="password"
                        value={this.state.signup.password}
                        onChange={this._onChange}
                        error={this.state.errors.password} />

                    <TextInput name="confirmPassword" label="Confirm" className="password" type="password"
                        value={this.state.signup.confirmPassword}
                        onChange={this._onChange}
                        error={this.state.errors.confirmPassword}
                        showErrorMessage={true} />

                    <fieldset className="form-button-group">
                        <button type="button" className="form-button button-default" onClick={this._create}>create</button>
                        <button type="button" className="form-button" onClick={this._cancel}>cancel</button>
                    </fieldset>
                </form>
            </section>

        );
    }

    _onSignup = (message) => {
        console.log('message:', message);
        if (message) {
            console.log(message);
            this.state.errors.username = message;
            this.setState({errors: this.state.errors});
        } else {
            authActions.login(this.state.signup.username, this.state.signup.password);
        }
    }

    _onLogin = (user) => {
        if (user) {
            this.context.router.push('/ideas');
        } else {
            console.log('something weird happened...');
        }
    }

    _onChange = (e) => {
        var field = e.target.name;
        var value = e.target.value;
        this.state.signup[field] = value;
        this.setState({signup: this.state.signup});
    }

    _create = (e) => {
        e.preventDefault();

        if (!this._formIsValid()) {
            return;
        }

        let user = {
            username: this.state.signup.username,
            firstName: this.state.signup.firstName,
            lastName: this.state.signup.lastName,
            email: this.state.signup.email,
            password: this.state.signup.password
        };
        authActions.signup(user);
    }

    _cancel = (e) => {
        e.preventDefault();
        this.context.router.push('/login');
    }

    _formIsValid = () => {
        let formIsValid = true;
        let requiredField = ['username', 'firstName', 'lastName', 'email', 'password'];

        this.state.errors = {};
        for (let f of requiredField) {
            if (this.state.signup[f].trim().length === 0) {
                this.state.errors[f] = 'required';
                formIsValid = false;
            }
        }
        if (this.state.signup.password !== this.state.signup.confirmPassword) {
            this.state.errors.confirmPassword = 'passwords must match';
            formIsValid = false;
        }

        this.setState({errors: this.state.errors});
        return formIsValid;
    }
}

export default SignupPage;

// angular2-node-express-mongodb/src/client/app/components/login/signup-page.component.ts
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
    templateUrl: 'app/components/login/signup-page.component.html'
})
export class SignupPageComponent implements OnInit {
    user: any;
    confirmPassword: string;
    form: FormGroup;
    formSubmitted: boolean;

    constructor(
        private _router: Router,
        private _authService: AuthService
    ) { }

    ngOnInit() {
        this.user = {
            username: '',
            firstName: '',
            lastName: '',
            email: '',
            password: ''
        };
        this.confirmPassword = '';

        let confirmPasswordValidator = (c: FormControl) => {
            return c.value === this.user.password ? null : {
                mustMatch: 'passwords must match'
            };
        };

        this.form = new FormGroup({
            username: new FormControl('', Validators.required),
            firstName: new FormControl('', Validators.required),
            lastName: new FormControl('', Validators.required),
            email: new FormControl('', Validators.required),
            password: new FormControl('', Validators.required),
            confirmPassword: new FormControl('', [Validators.required, confirmPasswordValidator])
        });
    }

    back(e: Event) {
        if (e) { e.preventDefault(); }
        this._router.navigate(['/login']);
    }

    create() {
        this.formSubmitted = true;
        if (this.form.valid) {
            this._authService.signup(this.user)
                .then(msg => {
                    if (msg) {
                        this.form.controls['username'].setErrors({ invalidUsername: msg });
                    } else {
                        this._authService.login(this.user.username, this.user.password)
                            .then(user => {
                                if (user) {
                                    this._router.navigate(['/ideas']);
                                } else {
                                    console.log('something weird happened...');
                                }
                            });
                    }
                });
        }
    }
}

<section>
    <h1 class="title">Create Account</h1>

    <ul class="actions">
        <li><a href="#" (click)="back($event)">back</a></li>
    </ul>

    <form [formGroup]="form" (ngSubmit)="create()">
        <id-text-input formControlName="username" label="Username" class="id"
            [(ngModel)]="user.username"
            [errors]="formSubmitted ? form.controls.username.errors : {}"
            [showErrorMessage]="form.controls.username.errors && !form.controls.username.errors.required"
            [autoFocus]="true">
        </id-text-input>

        <id-text-input formControlName="firstName" label="First Name" class="name"
            [(ngModel)]="user.firstName"
            [errors]="formSubmitted ? form.controls.firstName.errors : {}">
        </id-text-input>

        <id-text-input formControlName="lastName" label="Last Name" class="name"
            [(ngModel)]="user.lastName"
            [errors]="formSubmitted ? form.controls.lastName.errors : {}">
        </id-text-input>

        <id-text-input formControlName="email" label="Email" class="email" type="email"
            [(ngModel)]="user.email"
            [errors]="formSubmitted ? form.controls.email.errors : {}">
        </id-text-input>

        <id-text-input formControlName="password" label="Password" class="password" type="password"
            [(ngModel)]="user.password"
            [errors]="formSubmitted ? form.controls.password.errors : {}">
        </id-text-input>

        <id-text-input formControlName="confirmPassword" label="Confirm" class="password" type="password"
            [(ngModel)]="confirmPassword"
            [errors]="formSubmitted ? form.controls.confirmPassword.errors : {}"
            [showErrorMessage]="form.controls.confirmPassword.errors && !form.controls.confirmPassword.errors.required">
        </id-text-input>

        <fieldset class="form-button-group">
            <button type="submit" class="form-button button-default">create</button>
            <button type="button" class="form-button" (click)="back()">cancel</button>
        </fieldset>
    </form>
</section>
