// react-es6-node-graphql-mongodb/src/client/components/people/personViewPage.react.js
import React, {Component, PropTypes} from 'react';
import {Link} from 'react-router';
import moment from 'moment';
import {UserStore} from '../../stores/userStore';
import ViewField from '../common/viewField.react';

class PersonViewPage extends Component {
    static contextTypes = {
        router: PropTypes.object.isRequired
    }

    constructor(props) {
        super(props);
        this.state = {
            person: {}
        };
    }

    componentWillMount() {
        UserStore.getUserById(this.props.params.personId)
            .done(user => {
                this.setState({ person: user });
            });
    }

    render() {
        return (
            <section>
                <h1 className="title">Person Details</h1>

                <ul className="actions">
                    <li><Link to="/people">back</Link></li>
                </ul>

                <div>
                    <ViewField label="" value={this.state.person.firstName + ' ' + this.state.person.lastName} className="bottom-border" />
                    <ViewField label="Username" value={this.state.person.username} />
                    <ViewField label="Email" value={this.state.person.email} />
                    <ViewField label="Joined" value={moment(this.state.person.createdDate).format('M/DD/YYYY')} />
                </div>
            </section>
        );
    }
}

export default PersonViewPage;

// angular2-node-express-mongodb/src/client/app/components/people/person-view-page.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { UserService } from '../../services/user.service';

@Component({
    templateUrl: 'app/components/people/person-view-page.component.html'
})
export class PersonViewPageComponent implements OnInit {
    user: any;

    constructor(
        private _route: ActivatedRoute,
        private _userService: UserService
    ) { }

    ngOnInit() {
        this.user = {};

        let id = this._route.snapshot.params['id'];
        this._userService.getById(id)
            .then(user => this.user = user);
    }
}

<id-header></id-header>

<section>
    <h1 class="title">Person Details</h1>

    <ul class="actions">
        <li><a routerLink="/people">back</a></li>
    </ul>

    <div>
        <id-view-field label="" [value]="user.firstName + ' ' + user.lastName" class="bottom-border"></id-view-field>
        <id-view-field label="Username" [value]="user.username"></id-view-field>
        <id-view-field label="Email" [value]="user.email"></id-view-field>
        <id-view-field label="Joined" [value]="user.createdDate | idDateFormatter"></id-view-field>
    </div>
</section>
