// react-es6-node-graphql-mongodb/src/client/components/ideas/sub/proposersSection.react.js
import React, {Component, PropTypes} from 'react';
import ideaActions from '../../../actions/ideaActions';

class ProposersSection extends Component {
    static propTypes = {
        proposers: PropTypes.array.isRequired,
        onRemove: PropTypes.func.isRequired,
        onAdd: PropTypes.func.isRequired
    }

    render() {
        let proposers = this.props.proposers.map(proposer => {
            return (
                <li key={proposer._id}>
                    {proposer.firstName} {proposer.lastName}
                    <button type="button" onClick={this.props.onRemove.bind(this, proposer)}>x</button>
                </li>
            );
        });

        return (
            <fieldset className="form-group">
                <label className="form-label" for="ideaProposers">Proposers</label>
                <ul className="inline-form-list">
                    {proposers}
                </ul>
                <button type="button" className="inline-symbol" onClick={this.props.onAdd}>(+)</button>
            </fieldset>
        );
    }
}

export default ProposersSection;

// angular2-node-express-mongodb/src/client/app/components/ideas/proposers-section.component.ts
import {Component, Input, Output, EventEmitter} from '@angular/core';
import { IUser } from '../../services/user.service';

@Component({
    selector: 'id-proposers-section',
    templateUrl: 'app/components/ideas/proposers-section.component.html'
})
export class ProposersSectionComponent {
    @Input() proposers: any[];
    @Output() remove = new EventEmitter<IUser>();
    @Output() add = new EventEmitter<void>();

    onRemove(proposer: IUser) {
        this.remove.emit(proposer);
    }

    onAdd() {
        this.add.emit();
    }
}

<fieldset class="form-group">
    <label class="form-label" for="ideaProposers">Proposers</label>
    <ul class="inline-form-list">
        <li *ngFor="let proposer of proposers">
            {{proposer.firstName}} {{proposer.lastName}}
            <button type="button" (click)="onRemove(proposer)">x</button>
        </li>
    </ul>
    <button type="button" class="inline-symbol" (click)="onAdd()">(+)</button>
</fieldset>
