// react-es6-node-graphql-mongodb/src/client/components/ideas/sub/skillsSection.react.js
import React, {Component, PropTypes} from 'react';
import util from '../../../utilities/util';
import ideaActions from '../../../actions/ideaActions';

class SkillsSection extends Component {
    static propTypes = {
        skills: PropTypes.arrayOf(PropTypes.string).isRequired,
        allSkills: PropTypes.arrayOf(PropTypes.string).isRequired,
        onChange: PropTypes.func.isRequired
    }

    constructor(props) {
        super(props);
        this.state = {
            newSkill: '',
            showNewSkill: false
        };
    }

    render() {
        let keyCounter = 1;

        let index = 0;
        let ideaSkills = this.props.skills.map(skill => {
            return (
                <li key={keyCounter++}>
                    {skill} <button type="button" onClick={this._removeSkill.bind(this, index++)}>x</button>
                </li>
            );
        });

        let allSkills = this.props.allSkills.map(skill => {
            return <option key={keyCounter++} value={skill} />;
        });

        let newSkill = (
            <li className="skill-new">
                <input id="newSkill" list="newSkillData" value={this.state.newSkill} onChange={this._newSkillChanged}
                    onKeyUp={this._newSkillKeyUp} className="form-element" type="text" autoFocus={true} />
                <datalist id="newSkillData">{allSkills}</datalist>
                <button type="button" className="inline-symbol" onClick={this._saveSkill}>(+)</button>
                <button type="button" className="inline-symbol" onClick={this._cancelSkill}>(x)</button>
            </li>
        )

        return (
            <fieldset className="form-group">
                <label className="form-label" for="ideaSkills">Skills</label>
                <ul className="inline-form-list">
                    {ideaSkills}
                    {(() => {
                        if (this.state.showNewSkill) { return newSkill; }
                    })()}
                </ul>
                {(() => {
                    if (!this.state.showNewSkill) {
                        return (<button type="button" className="inline-symbol" onClick={this._addSkill}>(+)</button>);
                    }
                })()}
            </fieldset>
        );
    }

    _newSkillKeyUp = (e) => {
        if (e.keyCode === 13) {
            this._saveSkill(e);
        } else if (e.keyCode === 27) {
            this._cancelSkill(e);
        }
    }

    _newSkillChanged = (e) => {
        this.setState({newSkill: e.target.value});
    }

    _removeSkill = (index, e) => {
        e.preventDefault();
        this.props.skills.splice(index, 1);
        this.props.onChange('skills', this.props.skills);
    }

    _addSkill = (e) => {
        e.preventDefault();
        this.setState({showNewSkill: true});
    }

    _saveSkill = (e) => {
        e.preventDefault();
        if (util.isEmpty(this.state.newSkill)) {
            return;
        }

        let index = this.props.skills.indexOf(this.state.newSkill);
        if (index === -1) {
            this.props.skills.push(this.state.newSkill);
            this.props.onChange('skills', this.props.skills);
        }
        this.setState({newSkill: '', showNewSkill: false});
    }

    _cancelSkill = (e) => {
        e.preventDefault();
        this.setState({newSkill: '', showNewSkill: false});
    }
}

export default SkillsSection;

// angular2-node-express-mongodb/src/client/app/components/ideas/skills-section.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { Util } from '../../blocks/util/util.service';

@Component({
    selector: 'id-skills-section',
    templateUrl: 'app/components/ideas/skills-section.component.html'
})
export class SkillsSectionComponent implements OnInit {
    @Input() skills: string[] = [];
    @Output() skillsChange = new EventEmitter<string[]>();
    @Input() allSkills: string[] = [];

    newSkill: string;
    showNewSkill: boolean;

    constructor(private _util: Util) { }

    ngOnInit() {
        this.newSkill = '';
        this.showNewSkill = false;
    }

    newSkillKeyUp(e: KeyboardEvent) {
        if (e.keyCode === 13) {
            setTimeout(() => {
                this.saveSkill();
            });
        } else if (e.keyCode === 27) {
            this.cancelSkill();
        }
    }

    removeSkill(index: number) {
        this.skills.splice(index, 1);
        this.skillsChange.emit(this.skills);
    }

    saveSkill() {
        if (this._util.isEmpty(this.newSkill)) {
            return;
        }

        let index = this.skills.indexOf(this.newSkill);
        if (index === -1) {
            this.skills.push(this.newSkill);
            this.skillsChange.emit(this.skills);
        }
        this.newSkill = '';
        this.showNewSkill = false;
    }

    cancelSkill() {
        this.showNewSkill = false;
        this.newSkill = '';
    }

    addSkill() {
        this.showNewSkill = true;
    }
}

<fieldset class="form-group">
    <label class="form-label" for="ideaSkills">Skills</label>
    <ul class="inline-form-list">
        <li *ngFor="let skill of skills; let i=index">
            {{skill}} <button type="button" (click)="removeSkill(i)">x</button>
        </li>
        <li *ngIf="showNewSkill" class="skill-new">
            <input id="newSkill" list="newSkillData" class="form-element" type="text"
                [(ngModel)]="newSkill"
                (keyup)="newSkillKeyUp($event)"
                autofocus>
            <datalist id="newSkillData">
                <option *ngFor="let skill of allSkills" [value]="skill">{{skill}}</option>
            </datalist>
            <button type="button" class="inline-symbol" (click)="saveSkill()">(+)</button>
            <button type="button" class="inline-symbol" (click)="cancelSkill()">(x)</button>
        </li>
    </ul>
    <button *ngIf="!showNewSkill" type="button" class="inline-symbol" (click)="addSkill()">(+)</button>
</fieldset>
