// react-es6-node-graphql-mongodb/src/client/components/ideas/sub/tagsSection.react.js
import React, {Component, PropTypes} from 'react';
import util from '../../../utilities/util';
import ideaActions from '../../../actions/ideaActions';

class TagsSection extends Component {
    static propTypes = {
        tags: PropTypes.arrayOf(PropTypes.string).isRequired,
        allTags: PropTypes.arrayOf(PropTypes.string).isRequired,
        onChange: PropTypes.func.isRequired
    }

    constructor(props) {
        super(props);
        this.state = {
            newTag: '',
            showNewTag: false
        };
    }

    render() {
        let keyCounter = 1;

        let index = 0;
        let ideaTags = this.props.tags.map(tag => {
            return (
                <li key={keyCounter++}>
                    {tag} <button type="button" onClick={this._removeTag.bind(this, index++)}>x</button>
                </li>
            );
        });

        let allTags = this.props.allTags.map(tag => {
            return <option key={keyCounter++} value={tag} />;
        });

        let newTag = (
            <li className="tag-new">
                <input id="newTag" list="newTagData" value={this.state.newTag} onChange={this._newTagChanged}
                    onKeyUp={this._newTagKeyUp} className="form-element" type="text" autoFocus={true} />
                <datalist id="newTagData">{allTags}</datalist>
                <button type="button" className="inline-symbol" onClick={this._saveTag}>(+)</button>
                <button type="button" className="inline-symbol" onClick={this._cancelTag}>(x)</button>
            </li>
        )

        return (
            <fieldset className="form-group">
                <label className="form-label" for="ideaTags">Tags</label>
                <ul className="inline-form-list">
                    {ideaTags}
                    {(() => {
                        if (this.state.showNewTag) { return newTag; }
                    })()}
                </ul>
                {(() => {
                    if (!this.state.showNewTag) {
                        return (<button type="button" className="inline-symbol" onClick={this._addTag}>(+)</button>);
                    }
                })()}
            </fieldset>
        );
    }

    _newTagKeyUp = (e) => {
        if (e.keyCode === 13) {
            this._saveTag(e);
        } else if (e.keyCode === 27) {
            this._cancelTag(e);
        }
    }

    _newTagChanged = (e) => {
        this.setState({newTag: e.target.value});
    }

    _removeTag = (index, e) => {
        e.preventDefault();
        this.props.tags.splice(index, 1);
        this.props.onChange('tags', this.props.tags);
    }

    _addTag = (e) => {
        e.preventDefault();
        this.setState({showNewTag: true});
    }

    _saveTag = (e) => {
        e.preventDefault();
        if (util.isEmpty(this.state.newTag)) {
            return;
        }

        let index = this.props.tags.indexOf(this.state.newTag);
        if (index === -1) {
            this.props.tags.push(this.state.newTag);
            this.props.onChange('tags', this.props.tags);
        }
        this.setState({newTag: '', showNewTag: false});
    }

    _cancelTag = (e) => {
        e.preventDefault();
        this.setState({newTag: '', showNewTag: false});
    }
}

export default TagsSection;

// angular2-node-express-mongodb/src/client/app/components/ideas/tags-section.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { Util } from '../../blocks/util/util.service';

@Component({
    selector: 'id-tags-section',
    templateUrl: 'app/components/ideas/tags-section.component.html'
})
export class TagsSectionComponent implements OnInit {
    @Input() tags: string[] = [];
    @Output() tagsChange = new EventEmitter<string[]>();
    @Input() allTags: string[] = [];

    newTag: string;
    showNewTag: boolean;

    constructor(private _util: Util) { }

    ngOnInit() {
        this.newTag = '';
        this.showNewTag = false;
    }

    newTagKeyUp(e: KeyboardEvent) {
        if (e.keyCode === 13) {
            setTimeout(() => {
                this.saveTag();
            });
        } else if (e.keyCode === 27) {
            this.cancelTag();
        }
    }

    removeTag(index: number) {
        this.tags.splice(index, 1);
        this.tagsChange.emit(this.tags);
    }

    saveTag() {
        if (this._util.isEmpty(this.newTag)) {
            return;
        }

        let index = this.tags.indexOf(this.newTag);
        if (index === -1) {
            this.tags.push(this.newTag);
            this.tagsChange.emit(this.tags);
        }
        this.newTag = '';
        this.showNewTag = false;
    }

    cancelTag() {
        this.showNewTag = false;
        this.newTag = '';
    }

    addTag() {
        this.showNewTag = true;
    }
}

<fieldset class="form-group">
    <label class="form-label" for="ideaTags">Tags</label>
    <ul class="inline-form-list">
        <li *ngFor="let tag of tags; let i=index">
            {{tag}} <button type="button" (click)="removeTag(i)">x</button>
        </li>
        <li *ngIf="showNewTag" class="tag-new">
            <input id="newTag" list="newTagData" class="form-element" type="text"
                [(ngModel)]="newTag"
                (keyup)="newTagKeyUp($event)"
                autofocus>
            <datalist id="newTagData">
                <option *ngFor="let tag of allTags" [value]="tag">{{tag}}</option>
            </datalist>
            <button type="button" class="inline-symbol" (click)="saveTag()">(+)</button>
            <button type="button" class="inline-symbol" (click)="cancelTag()">(x)</button>
        </li>
    </ul>
    <button *ngIf="!showNewTag" type="button" class="inline-symbol" (click)="addTag()">(+)</button>
</fieldset>
