// react-es6-node-graphql-mongodb/src/client/components/ideas/sub/technologiesSection.react.js
import React, {Component, PropTypes} from 'react';
import util from '../../../utilities/util';
import ideaActions from '../../../actions/ideaActions';

class TechnologiesSection extends Component {
    static propTypes = {
        technologies: PropTypes.arrayOf(PropTypes.string).isRequired,
        allTechnologies: PropTypes.arrayOf(PropTypes.string).isRequired,
        onChange: PropTypes.func.isRequired
    }

    constructor(props) {
        super(props);
        this.state = {
            newTech: '',
            showNewTech: false
        };
    }

    render() {
        let keyCounter = 1;

        let index = 0;
        let ideaTechs = this.props.technologies.map(tech => {
            return (
                <li key={keyCounter++}>
                    {tech} <button type="button" onClick={this._removeTech.bind(this, index++)}>x</button>
                </li>
            );
        });

        let allTechs = this.props.allTechnologies.map(tech => {
            return <option key={keyCounter++} value={tech} />;
        });

        let newTech = (
            <li className="tech-new">
                <input id="newTech" list="newTechData" value={this.state.newTech} onChange={this._newTechChanged}
                    onKeyUp={this._newTechKeyUp} className="form-element" type="text" autoFocus={true} />
                <datalist id="newTechData">{allTechs}</datalist>
                <button type="button" className="inline-symbol" onClick={this._saveTech}>(+)</button>
                <button type="button" className="inline-symbol" onClick={this._cancelTech}>(x)</button>
            </li>
        )

        return (
            <fieldset className="form-group">
                <label className="form-label" for="ideaTechnologies">Technologies</label>
                <ul className="inline-form-list">
                    {ideaTechs}
                    {(() => {
                        if (this.state.showNewTech) { return newTech; }
                    })()}
                </ul>
                {(() => {
                    if (!this.state.showNewTech) {
                        return (<button type="button" className="inline-symbol" onClick={this._addTech}>(+)</button>);
                    }
                })()}
            </fieldset>
        );
    }

    _newTechKeyUp = (e) => {
        if (e.keyCode === 13) {
            this._saveTech(e);
        } else if (e.keyCode === 27) {
            this._cancelTech(e);
        }
    }

    _newTechChanged = (e) => {
        this.setState({newTech: e.target.value});
    }

    _removeTech = (index, e) => {
        e.preventDefault();
        this.props.technologies.splice(index, 1);
        this.props.onChange('technologies', this.props.technologies);
    }

    _addTech = (e) => {
        e.preventDefault();
        this.setState({showNewTech: true});
    }

    _saveTech = (e) => {
        e.preventDefault();
        if (util.isEmpty(this.state.newTech)) {
            return;
        }

        let index = this.props.technologies.indexOf(this.state.newTech);
        if (index === -1) {
            this.props.technologies.push(this.state.newTech);
            this.props.onChange('technologies', this.props.technologies);
        }
        this.setState({newTech: '', showNewTech: false});
    }

    _cancelTech = (e) => {
        e.preventDefault();
        this.setState({newTech: '', showNewTech: false});
    }
}

export default TechnologiesSection;

// angular2-node-express-mongodb/src/client/app/components/ideas/technologies-section.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { Util } from '../../blocks/util/util.service';

@Component({
    selector: 'id-technologies-section',
    templateUrl: 'app/components/ideas/technologies-section.component.html'
})
export class TechnologiesSectionComponent implements OnInit {
    @Input() technologies: string[] = [];
    @Output() technologiesChange = new EventEmitter<string[]>();
    @Input() allTechnologies: string[] = [];

    newTechnology: string;
    showNewTechnology: boolean;

    constructor(private _util: Util) { }

    ngOnInit() {
        this.newTechnology = '';
        this.showNewTechnology = false;
    }

    newTechnologyKeyUp(e: KeyboardEvent) {
        if (e.keyCode === 13) {
            setTimeout(() => {
                this.saveTechnology();
            });
        } else if (e.keyCode === 27) {
            this.cancelTechnology();
        }
    }

    removeTechnology(index: number) {
        this.technologies.splice(index, 1);
        this.technologiesChange.emit(this.technologies);
    }

    saveTechnology() {
        if (this._util.isEmpty(this.newTechnology)) {
            return;
        }

        let index = this.technologies.indexOf(this.newTechnology);
        if (index === -1) {
            this.technologies.push(this.newTechnology);
            this.technologiesChange.emit(this.technologies);
        }
        this.newTechnology = '';
        this.showNewTechnology = false;
    }

    cancelTechnology() {
        this.showNewTechnology = false;
        this.newTechnology = '';
    }

    addTechnology() {
        this.showNewTechnology = true;
    }
}

<fieldset class="form-group">
    <label class="form-label" for="ideaTechnologies">Technologies</label>
    <ul class="inline-form-list">
        <li *ngFor="let technology of technologies; let i=index">
            {{technology}} <button type="button" (click)="removeTechnology(i)">x</button>
        </li>
        <li *ngIf="showNewTechnology" class="technology-new">
            <input id="newTechnology" list="newTechnologyData" class="form-element" type="text"
                [(ngModel)]="newTechnology"
                (keyup)="newTechnologyKeyUp($event)"
                autofocus>
            <datalist id="newTechnologyData">
                <option *ngFor="let technology of allTechnologies" [value]="technology">{{technology}}</option>
            </datalist>
            <button type="button" class="inline-symbol" (click)="saveTechnology()">(+)</button>
            <button type="button" class="inline-symbol" (click)="cancelTechnology()">(x)</button>
        </li>
    </ul>
    <button *ngIf="!showNewTechnology" type="button" class="inline-symbol" (click)="addTechnology()">(+)</button>
</fieldset>
