// angular2-node-express-mongodb/src/client/app/components/common/person-search.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { Router } from '@angular/router';
import { Util } from '../../blocks/util/util.service';
import { UserService, IUser } from '../../services/user.service';

@Component({
    selector: 'id-person-search',
    templateUrl: 'app/components/common/person-search.component.html'
})
export class PersonSearchComponent {
    @Input() people: IUser[] = [];
    @Output() selectPerson = new EventEmitter<IUser>();
    @Output() close = new EventEmitter<void>();

    searchStr: string = '';
    searchResults: IUser[] = [];

    constructor(
        private _router: Router,
        private _util: Util,
        private _userService: UserService
    ) { }

    closeLightbox() {
        this.close.emit();
    }

    executeSearch() {
        if (this._util.isEmpty(this.searchStr)) {
            this.searchResults = [];
            return;
        }

        let str = this.searchStr.toLowerCase();
        let results = this.people.filter(p => {
            return p.firstName.toLowerCase().indexOf(str) > -1 ||
                p.lastName.toLowerCase().indexOf(str) > -1 ||
                p.username.toLowerCase().indexOf(str) > -1 ||
                p.email.toLowerCase().indexOf(str) > -1;
        });
        this.searchResults = results;
    }

    onSelectPerson(person: IUser) {
        this.selectPerson.emit(person);
        this.closeLightbox();
    }
}

<div class="person-search fade">
    <div class="person-search-container">
        <form (ngSubmit)="executeSearch()">
            <input type="text" name="searchStr" class="form-element small" [(ngModel)]="searchStr"[id-autofocus]="true">
            <button type="submit" class="hidden"></button>
            <button type="button" class="inline person-search-close" (click)="closeLightbox()">(close)</button>
        </form>

        <div class="person-search-results">
            <ul>
                <li *ngFor="let person of searchResults">
                    <button (click)="onSelectPerson(person)">
                        <span class="person-result-full-name">{{person.firstName}} {{person.lastName}}</span>
                        <span class="person-result-info">username: {{person.username}}</span>
                        <span class="person-result-info">{{person.email}}</span>
                    </button>
                </li>
            </ul>
        </div>
    </div>
</div>

// react-es6-node-graphql-mongodb/src/client/components/common/personSearch.react.js
import React, {Component, PropTypes} from 'react';
import {Link} from 'react-router';
import util from '../../utilities/util';

class PersonSearch extends Component {
    static propTypes = {
        people: PropTypes.arrayOf(PropTypes.object).isRequired,
        onSelect: PropTypes.func.isRequired,
        onClose: PropTypes.func.isRequired
    }

    constructor(props) {
        super(props);
        this.state = {
            searchStr: '',
            searchResults: []
        };
    }

    render() {
        let keyCounter = 1;

        let searchResults = this.state.searchResults.map(person => {
            return (
                <li key={keyCounter++}>
                    <button onClick={this._selectPerson.bind(this, person)}>
                        <span className="person-result-full-name">{person.firstName} {person.lastName}</span>
                        <span className="person-result-info">username: {person.username}</span>
                        <span className="person-result-info">{person.email}</span>
                    </button>
                </li>
            );
        });

        return (
            <div className="person-search fade">
                <div className="person-search-container">
                    <form onSubmit={this._executeSearch}>
                        <input className="form-element small" type="text" value={this.state.searchStr} onChange={this._onChange} autoFocus={true} />
                        <button type="submit" className="hidden"></button>
                        <button type="button" className="inline person-search-close" onClick={this.props.onClose}>(close)</button>
                    </form>

                    <div className="person-search-results">
                        <ul>
                            {searchResults}
                        </ul>
                    </div>
                </div>
            </div>
        );
    }

    _selectPerson = (person, e) => {
        e.preventDefault();
        this.props.onSelect(person);
    }

    _executeSearch = (e) => {
        e.preventDefault();

        let str = this.state.searchStr;
        if (util.isEmpty(str)) {
            return this.setState({searchResults: this.props.people});
        }

        let results = this.props.people.filter(p => {
            return p.firstName.toLowerCase().indexOf(str) > -1 ||
                p.lastName.toLowerCase().indexOf(str) > -1 ||
                p.username.toLowerCase().indexOf(str) > -1 ||
                p.email.toLowerCase().indexOf(str) > -1;
        });
        this.setState({searchResults: results});
    }

    _onChange = (e) => {
        e.preventDefault();
        this.setState({searchStr: e.target.value});
    }
}

export default PersonSearch;
