// angular2-node-express-mongodb/src/client/app/components/common/text-input.component.ts
import { Component, Input, Output, EventEmitter, forwardRef } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

@Component({
    selector: 'id-text-input',
    providers: [
        {
            provide: NG_VALUE_ACCESSOR,
            useExisting: forwardRef(() => TextInputComponent),
            multi: true
        }
    ],
    template: `
        <fieldset class="form-group">
            <label class="form-label" [attr.for]="name">{{label}}</label>
            <input
                [type]="type || 'text'"
                [id]="name"
                [name]="name"
                [class]="'form-element ' + (class || '')"
                [ngClass]="{'has-error': hasErrors}"
                [placeholder]="placeholder || ''"
                [(ngModel)]="value"
                (ngModelChange)="propagateChange($event)"
                [disabled]="disabled"
                [id-autofocus]="autoFocus">
            <span *ngIf="showErrorMessage && errorMessage" class="error-msg-inline">{{errorMessage}}</span>
        </fieldset>
    `
})
export class TextInputComponent implements ControlValueAccessor {
    @Input() name: string;
    @Input() label: string;
    @Input() class: string;
    @Input() value: string;
    @Input() placeholder: string;
    @Input() errors: any;
    @Input() showErrorMessage: boolean;
    @Input() type: string;
    @Input() disabled: boolean;
    @Input() autoFocus: boolean;

    propagateChange = (_: any) => { };
    hasErrors: boolean;
    errorMessage: string;

    ngDoCheck() {
        let keys = Object.keys(this.errors || {});
        this.hasErrors = keys.length > 0;
        this.errorMessage = this.showErrorMessage ? this.errors[keys[0]] : null;
    }

    writeValue(value: any): void {
        this.value = value;
    }

    registerOnChange(fn: any): void {
        this.propagateChange = fn;
    }

    registerOnTouched(): void { }
}

// react-es6-node-graphql-mongodb/src/client/components/common/textInput.react.js
import React, {Component, PropTypes} from 'react';
import util from '../../utilities/util';

class TextInput extends Component {
    static propTypes = {
        name: PropTypes.string.isRequired,
        label: PropTypes.string.isRequired,
        onChange: PropTypes.func,
        className: PropTypes.string,
        placeholder: PropTypes.string,
        value: PropTypes.string,
        error: PropTypes.string,
        disabled: PropTypes.bool,
        type: PropTypes.string,
        showErrorMessage: PropTypes.bool,
        autoFocus: PropTypes.bool
    }

    render() {
        return (
            <fieldset className="form-group">
                <label className="form-label" for={this.props.name}>{this.props.label}</label>
                <input type={this.props.type || 'text'}
                    name={this.props.name}
                    className={'form-element ' + (this.props.className || '') + (this.props.error && this.props.error.length > 0 ? ' has-error' : '')}
                    placeholder={this.props.placeholder}
                    ref={this.props.name}
                    value={this.props.value}
                    onChange={this.props.onChange}
                    disabled={this.props.disabled}
                    autoFocus={this.props.autoFocus} />
                {(() => {
                    if (this.props.showErrorMessage && !util.isEmpty(this.props.error)) {
                        return (<span className="error-msg-inline">{this.props.error}</span>);
                    }
                })()}

            </fieldset>
        );
    }
}

export default TextInput;
