// angular2-node-express-mongodb/src/client/app/components/common/view-field.component.ts
import {Component, Input} from '@angular/core';

@Component({
    selector: 'id-view-field',
    template: `
        <div class='view-group'>
            <div class="view-label">{{label}}</div>
            <div [class]="'view-element ' + (class || '')">{{value === null || value === undefined ? '&nbsp;' : value}}</div>
        </div>
    `
})
export class ViewFieldComponent {
    @Input() label: string;
    @Input() value: string;
    @Input() class: string;
}

// react-es6-node-graphql-mongodb/src/client/components/common/viewField.react.js
import React, {Component, PropTypes} from 'react';

class ViewField extends Component {
    static propTypes = {
        label: PropTypes.string.isRequired,
        className: PropTypes.string,
        value: PropTypes.string
    }

    render() {
        return (
            <div className='view-group'>
                <div className="view-label">{this.props.label}</div>
                <div className={'view-element ' + (this.props.className || '')}>{this.props.value}</div>
            </div>
        );
    }
}

export default ViewField;
