// angular2-node-express-mongodb/src/client/app/components/ideas/idea-list-page.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Util } from '../../blocks/util/util.service';
import { IdeaService, IIdea } from '../../services/idea.service';
import { UserService, IUser } from '../../services/user.service';

@Component({
    templateUrl: 'app/components/ideas/idea-list-page.component.html'
})
export class IdeaListPageComponent implements OnInit {
    private _sortDesc: boolean;

    ideas: IIdea[];
    showFilter: boolean;
    filter: string;

    constructor(
        private _router: Router,
        private _util: Util,
        private _ideaService: IdeaService,
        private _userService: UserService
    ) { }

    ngOnInit() {
        this._sortDesc = false;
        this.ideas = [];
        this.showFilter = false;
        this.filter = '';

        this._userService.getAll()
            .then(users => {
                this._ideaService.getAll(users)
                    .then(ideas => this.ideas = ideas);
            });
    }

    viewIdea(idea: IIdea) {
        this._router.navigate(['/ideas', idea._id]);
    }

    reverseSortOrder(e: Event) {
        e.preventDefault();
        this._sortDesc = !this._sortDesc;
        this._sortIdeas(this.ideas);
    }

    toggleFilter(e: Event) {
        e.preventDefault();
        this.showFilter = !this.showFilter;
        if (!this.showFilter) {
            this.filter = '';
        }
    }

    toList(arr: string[]) {
        return this._util.arrayToString(arr);
    }

    onFilterChange(value: string) {
        this.filter = value;
    }

    private _sortIdeas(ideas: IIdea[]) {
        ideas.sort(this._util.sortCompareFunc('name', this._sortDesc, (i: string) => i.toUpperCase()));
    }
}

<id-header></id-header>

<section>
    <h1 class="title">Ideas</h1>

    <ul class="actions">
        <li><a routerLink="/ideas/new">new</a></li>
        <li><a href="#" (click)="reverseSortOrder($event)">sort</a></li>
        <li><a href="#" (click)="toggleFilter($event)">filter</a></li>
    </ul>

    <id-list-filter *ngIf="showFilter" [(filter)]="filter" (close)="showFilter = false"></id-list-filter>

    <ul class="idea-list" *ngIf="ideas.length > 0">
        <li *ngFor="let idea of ideas | idIdeaFilter:filter">
            <button (click)="viewIdea(idea)">
                <span class="idea-list-name">{{idea.name}}</span>
                <span class="idea-list-summary">{{idea.summary}}</span>
                <span class="idea-list-info idea-list-info-first">votes: {{idea.votes.length}}</span>
                <span class="idea-list-info">tags: {{toList(idea.tags)}}</span>
                <span class="idea-list-info">skills: {{toList(idea.skills)}}</span>
                <span class="idea-list-info">techs: {{toList(idea.technologies)}}</span>
            </button>
        </li>
    </ul>
</section>

// react-es6-node-graphql-mongodb/src/client/components/ideas/ideaListPage.react.js
import React, {Component, PropTypes} from 'react';
import {Link} from 'react-router';
import util from '../../utilities/util';
import {IdeaStore} from '../../stores/ideaStore';
import ListFilter from '../common/listFilter.react';

class filteredIdeasPage extends Component {
    static contextTypes = {
        router: PropTypes.object.isRequired
    }

    constructor() {
        super();
        this._sortDesc = false;
        this.state = {
            ideas: [],
            filteredIdeas: [],
            filterStr: '',
            showFilter: false
        };
    }

    componentDidMount() {
        IdeaStore.getIdeaList()
            .done(ideas => {
                this._sortIdeas(ideas);
                this.setState({ ideas: ideas, filteredIdeas: ideas.slice() });
            });
    }

    render() {
        let content = this.state.filteredIdeas.map(idea => {
            return (
                <li key={idea._id}>
                    <button onClick={this._viewIdea.bind(this, idea._id)}>
                        <span className="idea-list-name">{idea.name}</span>
                        <span className="idea-list-summary">{idea.summary}</span>
                        <span className="idea-list-info idea-list-info-first">votes: {idea.votes.length}</span>
                        <span className="idea-list-info">tags: {this._toList(idea.tags)}</span>
                        <span className="idea-list-info">skills: {this._toList(idea.skills)}</span>
                        <span className="idea-list-info">techs: {this._toList(idea.technologies)}</span>
                    </button>
                </li>
            );
        });

        return (
            <section>
                <h1 className="title">Ideas</h1>

                <ul className="actions">
                    <li><Link to="/ideas/new">new</Link></li>
                    <li><a href="" onClick={this._reverseSortOrder}>sort</a></li>
                    <li><a href="" onClick={this._toggleFilter}>filter</a></li>
                </ul>

                {(() => {
                    if (this.state.showFilter) {
                        return (<ListFilter filterStr={this.state.filterStr} onChange={this._onFilterChange} />);
                    }
                })()}

                <ul className="idea-list">
                    {content}
                </ul>
            </section>
        );
    }

    _viewIdea = (id, e) => {
        e.preventDefault();
        this.context.router.push('/ideas/' + id);
    }

    _reverseSortOrder = (e) => {
        e.preventDefault();
        this._sortDesc = !this._sortDesc;
        this._sortIdeas(this.state.ideas);
        this.setState({ ideas: this.state.ideas });
    }

    _sortIdeas = (ideas) => {
        ideas.sort(
            util.sortCompareFunc('name', this._sortDesc, i => i.toUpperCase()));
    }

    _toggleFilter = (e) => {
        e.preventDefault();
        this.setState({ showFilter: !this.state.showFilter });
        if (this.state.showFilter) {
            this.setState({ filterStr: '', filteredIdeas: this.state.ideas.slice() });
        }
    }

    _onFilterChange = (e) => {
        let str = e.target.value.toLowerCase();
        this.state.filteredIdeas = this.state.ideas.filter(idea => {
            return idea.name.toLowerCase().indexOf(str) >= 0 ||
                idea.summary.toLowerCase().indexOf(str) >= 0;
        });
        this.setState({ filterStr: str, filteredIdeas: this.state.filteredIdeas });
    }

    _toList = (arr, prop) => {
        return util.arrayToString(arr, prop);
    }
}

export default filteredIdeasPage;
